### ISSUE TITLE
intel ax200 AirportItlwm.kext 使用无法连接网络

### ISSUE THREAD

**Issue by ningye2012** [Whosydd/MSI-B450m-Hackintosh-BigSur#1]
首先感谢您的EFI
在使用中安装了PCI-e转换卡来使用AX200，但驱动正常，添加网络也可以看到热点，但输入密码就是无法连接，不知何故？请问您是使用的转接卡还是nvrm第二卡槽？谢谢！

**Comment by whosydd** [comment]
我刚刚更新了11.1的EFI文件，目前正在使用中，解决了一些问题，建议你可以尝试下~

> 首先感谢您的EFI
> 在使用中安装了PCI-e转换卡来使用AX200，但驱动正常，添加网络也可以看到热点，但输入密码就是无法连接，不知何故？请问您是使用的转接卡还是nvrm第二卡槽？谢谢！
