### ISSUE TITLE
您好，b450m 迫击炮需要解锁cfg吗？

### ISSUE THREAD

**Issue by ghost** [Whosydd/MSI-B450m-Hackintosh-BigSur#2]
您好，b450m 迫击炮需要解锁cfg吗？

**Comment by whosydd** [comment]
我没有去特意搞这个，你如果想追求完美，可以去百度下，有不少教程的

**Comment by ghost** [comment]
您好，我出现了 device is write locked  请问有什么解决办法吗

**Comment by whosydd** [comment]
因为我已经对原版的efi文件进行了修改，如果你是在安装黑苹果的时候报错，建议你可以先使用[原版的EFI文件](https://github.com/Tyrone2333/r5-2600-b450m-bazooka-5700-hackintosh)进行安装，或者尝试使用其他EFI文件，成功安装之后再将EFI替换回来。（我就是这样搞的，试过了好几个EFI才装成功，之后再找个合适的替换。因为我也是个半吊子，只能在别人配置好的EFI中进行修改。。。）

**Comment by ghost** [comment]
好的，今晚试下，谢谢
