### ISSUE TITLE
我可以用 那个 不带 airport 前缀的驱动， 但是AirportItlwm.kext 不能联网

### ISSUE THREAD

**Issue by Petelin** [Whosydd/MSI-B450m-Hackintosh-BigSur#3]
请问你除了这个EFI以外，对系统还做过什么特别的设置吗？

**Comment by whosydd** [comment]
https://github.com/heyxiaobai/MSI-B450m-MORTAR-Hackintosh
建议你可以参考该rep，我只是去掉了音频驱动，添加了wifi和蓝牙驱动，其他都没有更改，有关wifi相关的问题可以[直接点这里查看](https://openintelwireless.github.io/)
